<?php
// fees.php

$fees = [
  "FIL1" => ["name" => "FILING FEE - RA 9048", "value" => "1000.00"],
  "FIL2" => ["name" => "FILING FEE - RA 10172/CFN", "value" => "3000.00"],
  "LRF"  => ["name" => "LATE REGISTRATION FEE", "value" => "400.00"],
  "REG"  => ["name" => "REGISTRATION FEE", "value" => "300.00"],
  "SEC"  => ["name" => "SECRETARY'S FEE", "value" => "200.00"],
  "LEG"  => ["name" => "LEGITIMATION FEE", "value" => "1000.00"],
  "MAF"  => ["name" => "MARRIAGE APPLICATION FEE", "value" => "1000.00"],
  "CCF"  => ["name" => "COUNSELLING FEE", "value" => "300.00"],
  "SOL"  => ["name" => "SOLEMNIZATION FEE", "value" => "200.00"],
  "SUP"  => ["name" => "SUPPLEMENTAL FEE", "value" => "1000.00"],
  "CEM"  => ["name" => "CEMETERY FEE", "value" => "1000.00"],
  "MF"   => ["name" => "MUNICIPAL FORM 103", "value" => "300.00"],
  "CTD"  => ["name" => "CERTIFICATION FEE (TD)", "value" => "200.00"],
  "CPH"  => ["name" => "CERTIFICATION FEE (PH)", "value" => "200.00"],
  "CTNI" => ["name" => "CERT. FEE (IMPROVEMENT)", "value" => "200.00"],
  "CNP"  => ["name" => "CERTIFICATION FEE (NPD)", "value" => "200.00"],
  "OIF"  => ["name" => "OCULAR INSPECTION FEE", "value" => "300.00"],
  "VER"  => ["name" => "VERIFICATION FEE", "value" => "300.00"],
  "URI"  => ["name" => "URINALYSIS", "value" => "100.00"],
  "PT"   => ["name" => "PREGNANCY TEST", "value" => "100.00"],
  "FEC"  => ["name" => "FECALYSIS", "value" => "100.00"],
  "FOB"  => ["name" => "FOBT", "value" => "300.00"],
  "CBC"  => ["name" => "CBC W/ PC", "value" => "200.00"],
  "BT"   => ["name" => "BLOOD TYPING", "value" => "100.00"],
  "HB"   => ["name" => "HBsAG", "value" => "200.00"],
  "SYP"  => ["name" => "SYPHILIS", "value" => "200.00"],
  "DENG" => ["name" => "DENGUE NS1", "value" => "300.00"],
  "GLU"  => ["name" => "GLUCOSE (FBS/RBS)", "value" => "150.00"],
  "TRI"  => ["name" => "TRIGLYCERIDE", "value" => "150.00"],
  "TC"   => ["name" => "TOTAL CHOLESTEROL", "value" => "150.00"],
  "HDL"  => ["name" => "HDL CHOLESTEROL", "value" => "150.00"],
  "LDL"  => ["name" => "CHOLESTEROL", "value" => "150.00"],
  "BUA"  => ["name" => "BUA", "value" => "150.00"],
  "CREA" => ["name" => "CREATININE", "value" => "150.00"],
  "BUN"  => ["name" => "BUN", "value" => "150.00"],
  "SGPT" => ["name" => "SGPT/ALT", "value" => "150.00"],
  "SGOT" => ["name" => "SGOT/AST", "value" => "150.00"],
  "HEL"  => ["name" => "NO HELMET", "value" => "150.00"],
  "NDL"  => ["name" => "DRIVING W/O VALID LICENSE", "value" => "500.00"],
  "OBS"  => ["name" => "OBSTRUCTION", "value" => "200.00"],
  "ILL"  => ["name" => "ILLEGAL PARKING", "value" => "200.00"],
  "BLOCK"=> ["name" => "BLOCKING PEDESTRIAN LANE", "value" => "200.00"],
  "DOB"  => ["name" => "DOUBLE PARKING", "value" => "200.00"],
  "MUFF" => ["name" => "NOISY MUFFLER", "value" => "2500.00"],
  "RECK" => ["name" => "RECKLESS/ARROGANT DRIVER", "value" => "500.00"],
  "EVR"  => ["name" => "EXPIRED VEHICLE REG.", "value" => "2500.00"],
  "DEF"  => ["name" => "NO/DEFECTIVE PARTS", "value" => "500.00"],
  "ILLMOD"=>["name" => "ILLEGAL MODIFICATION", "value" => "500.00"],
  "POT"  => ["name" => "PASSENGER ON TOP", "value" => "150.00"],
  "DIS"  => ["name" => "DISREGARDING OFFICER", "value" => "150.00"],
  "COL"  => ["name" => "COLORUM", "value" => "2500.00"],
  "NTB"  => ["name" => "NO TRASH BIN", "value" => "1000.00"],
  "CHAR" => ["name" => "OVER/UNDER CHARGING", "value" => "500.00"],
  "SAN"  => ["name" => "DRIVING IN SANDO/SHORT", "value" => "200.00"],
  "OVER" => ["name" => "OVERLOADED", "value" => "500.00"],
  "DRAG" => ["name" => "DRAG RACING", "value" => "1000.00"],
  "NVS"  => ["name" => "NO VISA STICKER", "value" => "300.00"],
  "FAIL" => ["name" => "FAILURE TO PRESENT EOV CARD", "value" => "200.00"],
  "POST" => ["name" => "POSTING FEE", "value" => "200.00"],
  "LOAD" => ["name" => "PAYLOADER", "value" => "2500.00"],
  "DT"   => ["name" => "DUMPTRUCK", "value" => "1000.00"],
  "BACK" => ["name" => "BACKHOE", "value" => "2500.00"],
  "CRANE"=> ["name" => "CRANE", "value" => "2500.00"],
  "BULL" => ["name" => "BULLDOZERS", "value" => "2500.00"],
  "GRADE"=> ["name" => "GRADER", "value" => "2500.00"],
  "DOC"  => ["name" => "DOCUMENTARY STAMP", "value" => "30.00"],
  "PED"  => ["name" => "PEDDLERS", "value" => "50.00"],
  "PTR"  => ["name" => "PROFESSIONAL TAX RECEIPT", "value" => "300.00"],
  "SPF"  => ["name" => "SPECIAL PERMIT FEE", "value" => "1000.00"],
  "NBS"  => ["name" => "NEW BORN SCREENING", "value" => "1750.00"],
  "OCCU" => ["name" => "OCCUPATIONAL FEE", "value" => "200.00"],
  "VISA" => ["name" => "VISA STICKER", "value" => "200.00"],
  "MTOP" => ["name" => "MTOP", "value" => "200.00"],
  "AF"   => ["name" => "PAYMENT OF AF #51", "value" => "200.00"],
  "POL"  => ["name" => "POLLUTION", "value" => "200.00"],
  "SUPV" => ["name" => "SUPERVISION FEE", "value" => "50.00"],
  "TER"  => ["name" => "TERMINAL FEE", "value" => "1000.00"],
  "SPF1" => ["name" => "SANITARY PERMIT FEE", "value" => "250.00"],
  "SPF2" => ["name" => "SANITARY PERMIT FEE", "value" => "300.00"],
  "MC"   => ["name" => "MAYOR'S CLEARANCE FEE", "value" => "200.00"],
  "MED"  => ["name" => "MEDICAL CERTIFICATE", "value" => "200.00"],
  "LDF"  => ["name" => "LDF", "value" => "100.00"],
  "VERMI"=> ["name" => "VERMI-COMPOST", "value" => "250.00"],
  "CERT" => ["name" => "CERTIFICATION FEE", "value" => "200.00"],
];
